version: "3.9"
services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HOST=db
      - PORT=${PG_PORT}
      - NAME=${POSTGRES_DB}
      - USER=${POSTGRES_USER}
      - PASS=${POSTGRES_PASSWORD}

  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:${PG_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 1s
      retries: 10
    restart: unless-stopped