spring:
  config:
    activate:
      on-profile: debug
  datasource:
    url: jdbc:h2:mem:mydb
    username: myuser
    password: mypass
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    generate-ddl: false