spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mydb
    username: myuser
    password: mypass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: validate

token:
  secret:
    key: z8MUdQfvoH4m3teWEkN/QizSW3XPlZ/zyJeQvQ3YOXp/09Iwl2TVsD+pi1Azd57M
    expiration: 123456789