server:
  port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/security/**
          filters:
            - RewritePath=/security(?<segment>/?.*), $\{segment}
            - TokenPreFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}
            - TokenPreFilter
        - id: hotel-service
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel-service/**
          filters:
            - RewritePath=/hotel-service(?<segment>/?.*), $\{segment}
            - TokenPreFilter

  application:
    name: API-GATEWAY
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
