databaseChangeLog:
  - changeSet:
      id: 1695558763437-1
      author: twenty_one_thirteen (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createSequence:
            incrementBy: 50
            sequenceName: guestinfo_seq
            startValue: 1
  - changeSet:
      id: 1695558763437-2
      author: twenty_one_thirteen (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createSequence:
            incrementBy: 50
            sequenceName: hotel_seq
            startValue: 1
  - changeSet:
      id: 1695558763437-3
      author: twenty_one_thirteen (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createSequence:
            incrementBy: 50
            sequenceName: room_seq
            startValue: 1
  - changeSet:
      id: 1695558763437-4
      author: twenty_one_thirteen (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createSequence:
            incrementBy: 50
            sequenceName: user_seq
            startValue: 1
  - changeSet:
      id: 1695558763437-5
      author: twenty_one_thirteen (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createSequence:
            incrementBy: 50
            sequenceName: wallet_seq
            startValue: 1
  - changeSet:
      id: 1695558763437-6
      author: twenty_one_thirteen (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_guestinfo
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: name
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: surname
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: dateofbirth
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: passport
                  type: VARCHAR(255)
            tableName: guestinfo
  - changeSet:
      id: 1695558763437-7
      author: twenty_one_thirteen (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_hotel
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: name
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: hotelclass
                  type: VARCHAR(255)
              - column:
                  name: userscore
                  type: BIGINT
            tableName: hotel
  - changeSet:
      id: 1695558763437-8
      author: twenty_one_thirteen (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_room
                  name: id
                  type: BIGINT
              - column:
                  name: hotelid
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: roomclass
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: maxguestscount
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: roomnumber
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: floor
                  type: BIGINT
            tableName: room
  - changeSet:
      id: 1695558763437-9
      author: twenty_one_thirteen (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_user
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: name
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: login
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: pass
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: date0fbirth
                  type: DATETIME
            tableName: user
  - changeSet:
      id: 1695558763437-10
      author: twenty_one_thirteen (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_wallet
                  name: id
                  type: BIGINT
              - column:
                  name: userid
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: balance
                  type: BIGINT
            tableName: wallet
  - changeSet:
      id: 1695558763437-11
      author: twenty_one_thirteen (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: hotelid
            baseTableName: room
            constraintName: FK_ROOM_ON_HOTELID
            referencedColumnNames: id
            referencedTableName: hotel
  - changeSet:
      id: 1695558763437-12
      author: twenty_one_thirteen (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: userid
            baseTableName: wallet
            constraintName: FK_WALLET_ON_USERID
            referencedColumnNames: id
            referencedTableName: user

